stages:
  # - test
  - build_image
  # - deploy_vm
  # - deploy_k8s

variables:
  GCP_PROJECT_NAME: nownews-analytics
  AR_PROJECT_NAME: nodejs-repo
  AR_TARGET: asia-docker.pkg.dev
  PROJECT_NAME: nodejs-template
  APP_VERSION: 2.4
  CLOUDRUN_SERVICE: my-service2

# test_job:
#   image: node:14.18.0
#   stage: test
#   only:
#     - master
#   script:
#     - cp /gitlab-runner/config/config.js ./
#     - yarn install
#     - npm run test 
#   tags: 
#     - nownews-docker-runner   

publish_image:      
  image: google/cloud-sdk:alpine
  stage: build_image  
  only:
    - main
  services:
    - name: docker:dind
  script:
    - sh ./shell/push_to_cloudrun.sh

    # push to private registry
    # - docker tag nodejs-template registry.linx.website/nodejs-template:${NODEJS_APP_VERSION}
    # - docker push registry.linx.website/nodejs-template:${NODEJS_APP_VERSION}
  tags:
    - nownews-docker-runner

#   image: node:14.18.0
#   stage: deploy_vm
#   only:
#     - master
#   script:
#     # tail -f /opt/tomcat/logs/catalina.2023-03-01.log -n 30  
#     - ssh gitlab-runner@172.16.200.6 "cd /devops/ansible/ && sudo ansible-playbook -i ./host/stg ./yaml/cicd/restart_service.yml --extra-vars 'host=stg-bn-rss01'"
#   tags:
#     - nown

# deply_job:
#   image: node:14.18.0
#   stage: deploy_vm
#   only:
#     - master
#   script:
#     # tail -f /opt/tomcat/logs/catalina.2023-03-01.log -n 30  
#     - ssh gitlab-runner@172.16.200.6 "cd /devops/ansible/ && sudo ansible-playbook -i ./host/stg ./yaml/cicd/restart_service.yml --extra-vars 'host=stg-bn-rss01'"
#   tags:
#     - nownews-docker-runner


# test1_job:
#   image: node:14.18.0
#   stage: test1
#   only:
#     - master
#   script:
#     - echo "$CI_JOB_TOKEN"
#     - echo "$CI_COMMIT_BRANCH"
#     - echo "$ENV_ACCOUNT"
#     - echo "$CI_REGISTRY"
#     - echo "$GITLAB_APP_REGISTRY"
#     - echo "$VERSION_NUMBER"
#     - echo "$CI_PIPELINE_SOURCE"
#     - echo "$DOCKERFILE_DIR"
#   tags: 
#     - nownews-docker-runner 
